# Generated by Django 3.2.4 on 2022-03-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='lastUnreadMessageUser1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='lastUnreadMessageUser2',
            field=models.IntegerField(null=True),
        ),
    ]
