# Generated by Django 3.2.4 on 2022-03-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger_backend', '0002_auto_20220323_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='lastUnreadMessageUser1',
            new_name='lastReadMessageUser1',
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='lastUnreadMessageUser2',
            new_name='lastReadMessageUser2',
        ),
    ]
